### ISSUE TITLE
Filter creating hangs when duplicate hashes are provided

### ISSUE THREAD

**Issue by SirWindfield** [ayazhafiz/xorf#25]
Took me some while to find the underlying issue. When passing a value twice to the same XOR filter, the filter hangs indefinitely. Here is a MCVE: https://github.com/SirWindfield/xorf-bug.

Looks like it hangs inside the loop statement as it can't break out of it. Not sure if you want to tackle this one down. Some ideas:

- Add a section to the documentation that duplicate values are not supported and result in an infinite loop.
- Add a `debug_assert` statement that checks the values for duplicates during debug builds
- Break out of the loop even if duplicate values are provided by ignoring them or by panicking/return Err.

**Comment by ayazhafiz** [comment]
This is an inherent limitation in Graf & Lemire's paper introducing xor filters (see https://arxiv.org/pdf/1912.08258.pdf, section 3.2) because of the construction of space-efficient hyper graphs as described in [Bothelo et.al. 07](https://homepages.dcc.ufmg.br/~nivio/papers/wads07.pdf). The problem is that we schedule keys from hashsets that have exactly one value, and since the hash functions are not changed during a single attempt to create an xor filter (see algorithm 2 in Graf & Lemire) two identical values will lead to a situation where no hashset ever has exactly one value.

I haven't looked into it but my intuition suggests that this cannot be improved without space/cycle costs, and a quick scan through Bothelo's work suggests similarly. Not sure if improvements have been made since 2007, but fuse graphs work similarly and Graf & Lemire published in 2019, so I think this is the state of the art.

> Add a section to the documentation that duplicate values are not supported and result in an infinite loop.

Probably the most reasonable thing to do, I think require folks to introduce a pre-processing step to dedupe values is fine. Filter construction is relatively expensive anyway so this should not be a problem for most use cases.

> Add a `debug_assert` statement that checks the values for duplicates during debug builds

This is probably reasonable too in terms of experience

> Break out of the loop even if duplicate values are provided by ignoring them or by panicking/return Err.

I am not in favor of this, keeping track of duplicate values is likely to be very expensive especially for large filters (if not in a debug context).
