### ISSUE TITLE
8-bit false positive rate tests fail suspiciously often

### ISSUE THREAD

**Issue by saethlin** [ayazhafiz/xorf#38]
I found this test failure in a recent crater run https://crater-reports.s3.amazonaws.com/pr-90799/master%2362efba8a050c64249dab942951bb28f710208bc8/reg/xorf-0.8.0/log.txt

I ran the tests locally a few thousand times times with `--no-fail-fast`, and got a 7% failure rate on `bfuse8::test::test_false_positives`, 7% failure rate on `fuse8::test::test_false_positives`, and 1% failure rate on `xor8::test::test_false_positives`, which combine to an aggregate 14% failure rate for the whole test suite.

Are we sure these tests are accurate? The false positive thresholds in terms of value and in terms of the number of significant figures they use vary a lot. The 16-bit tests check
https://github.com/ayazhafiz/xorf/blob/1284ce7816b99041ab44df2157922176d6325630/src/fuse16.rs#L153
And the `bfuse8` and `fuse8` tests check
https://github.com/ayazhafiz/xorf/blob/1284ce7816b99041ab44df2157922176d6325630/src/fuse8.rs#L153
And the `xor8` test checks
https://github.com/ayazhafiz/xorf/blob/1284ce7816b99041ab44df2157922176d6325630/src/xor8.rs#L135

Perhaps https://github.com/ayazhafiz/xorf/commit/6af4fdd149ca8afd8b70faf3da7cfc14e1b854e5 should have updated the other 8-bit false positive rates? I would prefer to see the threshold raised even farther to produce a false positive rate much closer to 0.1%. I would put up a PR to do this, but I don't know the math behind these values, and perhaps the authors do. If not, I'm happy to select a value empirically.

**Comment by ayazhafiz** [comment]
The false positive rates are theoretical and correct at the limit. The reason that there are sporadic test failures is that the tests generate (pseudo)random inputs, and since we can’t generate infinite size inputs, there is no guarantee the algorithm will behave as it does at the asymptote. What we really want to check is that “for large inputs, we behave somewhere close to the optimal behavior”.

The bounds that are in the test are that “somewhere close” choice, but you’re right, there is no reason that the tests would always behave in those bounds. I just chose them because in most cases, the test works out, and the “best case” is what we really care about.

One way to resolve this is to run the tests a number of times until we get the “best case” we’re looking for, or bail out if we don’t get what we’re looking for after some iterations. Based on your experiments, maybe 5 reruns is enough (1/7^5 is small enough to hopefully never happen). Or we could use deterministic inputs. I’m not sure; so far I’ve been doing what’s easiest, because I’m okay running tests several times to get the best looking output. But I’m open to suggestions.

Thanks for finding and raising visibility on this, by the way! It’s probably something I should have resolved eventually.

**Comment by saethlin** [comment]
> The false positive rates are theoretical and correct at the limit.

I don't think that is right. I'm new to think but based on what I can get from the paper, the false positive rate for xor filters is `1 / (2^k)` where `k` is the number of bits in the fingerprint. That means the expected false positive rate for an 8-bit filter is 0.390625% and the expected false positive rate for a 16-bit filter is ~0.00152587890625%. The tests check for 0.02%. I suspect this value originates in a transcription error from Table 3, which documents a FPP (which is always % in this paper) of 0.002 for the 16-bit filters. If I plug the values I get from that formula into the tests in this crate, I get failure rates for all the false positive tests of 40-50%. Which makes sense, the expected false positive rate is an expected value for some distribution and our sample distributions are quite large, so these tests basically just dance about a tiny space right near the expected value.

It also occurred to me just now that these tests only check for one side of the distribution. That is why what looks like a transcription error has gone un-seen for so long. I think the assertion should be that the false positive rate observed is within some bounds, and those bounds should be chosen to produce a low test failure rate. My stats is pretty rusty, normally you'd derive these bounds from the theoretical distribution but if it were up to me I'd just do this empirically by running the tests in a loop for a few hours to sample the distribution myself.

Of course we don't _have_ to do that, who really cares if the filters magically get really good one day. But it would be a good guard against such errors in the bounds.

> Thanks for finding and raising visibility on this, by the way! It’s probably something I should have resolved eventually.

You're welcome! It's good to be appreciated.

**Comment by ayazhafiz** [comment]
> That means the expected false positive rate for an 8-bit filter is 0.390625% and the expected false positive rate for a 16-bit filter is ~0.00152587890625%. The tests check for 0.02%.

No, the tests for 8bit filters check <0.4% as you noted in your first comment. You're right about the 16-bit filters being off by an order of magnitude; I think that was a genuine typo on my end.

> If I plug the values I get from that formula into the tests in this crate, I get failure rates for all the false positive tests of 40-50%. Which makes sense, the expected false positive rate is an expected value for some distribution and our sample distributions are quite large, so these tests basically just dance about a tiny space right near the expected value.

Yes, this is because we can only expect the false positive rate to be truly exact at the asymptote; with a finite number of keys, it need not be exactly the theoretical bound, as you note.

> I think the assertion should be that the false positive rate observed is within some bounds, and those bounds should be chosen to produce a low test failure rate.

I'm fine with just testing for the best case (lowest false positive rate). I don't really care about the worst case FPP. IMO this is one of those applications where we get a lot more out of determining what the best case for users is, rather than what the pathological case is.

If you would like to send a patch to fix the false positive checks for 16bit filters and some utility to run the tests a number of times until we get a good-looking result (or some other method you see fit), I'd be happy to accept it.
