### ISSUE TITLE
try_from with an iterator of keys

### ISSUE THREAD

**Issue by vlovich** [ayazhafiz/xorf#59]
Currently BinaryFuse64 requires you to pass a contiguous array of values. However, it only really needs an iterator. Would be nice to be able to supply an iterator (e.g. something like `non_contiguous_keys_structure.iter().map(|k: &[u8]| xxh3_hash(k))`). Probably requires `ExactSizeIterator` since the exact size is needed before iteration.

**Comment by ayazhafiz** [comment]
Agreed, happy to accept a patch for this!
________________________________
From: Vitali Lovich ***@***.***>
Sent: Thursday, October 27, 2022 12:58:19 PM
To: ayazhafiz/xorf ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ayazhafiz/xorf] try_from with an iterator of keys (Issue #59)


Currently BinaryFuse64 requires you to pass a contiguous array of values. However, it only really needs an iterator. Would be nice to be able to supply an iterator (e.g. something like non_contiguous_keys_structure.iter().map(|k: &[u8]| xxh3_hash(k))). Probably requires ExactSizeIterator since the exact size is needed before iteration.

**Comment by vlovich** [comment]
Done
